unique_ids:
  forms:
    AboutForm: '1716930814470158975048382.48788'
    ContactForm: '1716930754758514237090921.29834'
    MainPage: UME4OWHD4WIFIYWQQPF6TGQDEQUZDBQG
  modules: {}
  server_modules: {}
  assets:
    standard-page.html: I44Z4KQUTC2HKAIAVWTMK5L3GUQDGBOG
    theme.css: JHATFAFEKAHXUSXGD3HUQZ7QDGWVNY6J
  scripts: {}
